### ISSUE TITLE
no libgps

### ISSUE THREAD

**Issue by wawachen** [swri-robotics/gps_umd#12]
when I  catkin_make this package, it said cannot find libgps, so how to deal with it?

**Comment by kriskozak** [comment]
You should be able to install it via apt. I think you may need both libgps20 and libgps-dev.

`sudo apt-get install libgps20 libgps-dev`

**Comment by pjreed** [comment]
Using `rosdep` is the preferred way to install system dependencies for ROS packages.  You can read the documentation for it here: http://wiki.ros.org/rosdep
