### ISSUE TITLE
Change behavior in utm_odometry_node to not publish "no fix" info messages

### ISSUE THREAD

**Issue by shahvi** [swri-robotics/gps_umd#15]
Hi,
We have an underwater robot which operates long time periods without GPS fixes.  The "no fix" info messages from the utm_odometry_node fill up our log files.  This would be equally problem some for robots that operate indoors for a long time.
If noone has an objection, I suggest changing the [line](https://github.com/swri-robotics/gps_umd/blob/c3660f3784ea162692d84d1bf0a90c81f7da6e6d/gps_common/src/utm_odometry_node.cpp#L21) to `ROS_DEBUG`.
If this is acceptable I can submit a PR.

**Comment by pjreed** [comment]
That works for me, possibly even a `ROS_DEBUG_THROTTLE`.
