### ISSUE TITLE
Noetic release

### ISSUE THREAD

**Issue by Timple** [swri-robotics/gps_umd#27]
Would you mind releasing these packages also for the newest distribution ROS Noetic? :)

**Comment by pjreed** [comment]
You bet, I have opened a PR for it here: https://github.com/ros/rosdistro/pull/25065

**Comment by Timple** [comment]
Great!

**Comment by Timple** [comment]
And here we go! https://discourse.ros.org/t/new-packages-for-noetic-2020-06-05/14493
