### ISSUE TITLE
gpsd_client rtk support

### ISSUE THREAD

**Issue by nxdefiant** [swri-robotics/gps_umd#33]
Hi,

I noticed that gpsd_client reports -1 as status on the /extended_fix topic when status reported by gpsd is Real-Time Kinematic fixed or float.

I also noticed that the RTK-types are missing in the [GPSStatus-message](https://github.com/swri-robotics/gps_umd/blob/master/gps_common/msg/GPSStatus.msg). Any preference for the integer values for RTK-fixed and RTK-float before I try to patch gpsd_client?

Because I wonder where the 18 and 33 did come from:
```
int16 STATUS_DGPS_FIX=18 # Fixed with DGPS
int16 STATUS_WAAS_FIX=33 # Fixed with WAAS
```

**Comment by pjreed** [comment]
I'm not sure where those values originally came from; it looks like they were added long before we started maintaining this package.  I don't have any preference for those types, though, so feel free to add whatever makes sense to you.

**Comment by nxdefiant** [comment]
ok, to be honest, after looking at the code: It would be much easier if the status of the ros message would simply carry the status of the gpsd gps_data_t struct, but that would be an incompatible status, e.g. STATUS_NO_FIX of gpsd_client is -1 while for gpsd it is 0.

**Comment by nxdefiant** [comment]
Simply passing the status from gpsd to the ros message would also make future changes easier, see [gps.h: Move gps_data_t.status to gps_fix_t.status
](https://gitlab.com/gpsd/gpsd/-/commit/29991d6ffeb41ecfc8297db68bb68be0128c8514)

**Comment by danthony06** [comment]
I believe this was addressed by https://github.com/swri-robotics/gps_umd/pull/93 and https://github.com/swri-robotics/gps_umd/pull/94
