### ISSUE TITLE
Broken links for documentation

### ISSUE THREAD

**Issue by robogeekcanada** [swri-robotics/gps_umd#52]
The code link to the [tutorial](http://wiki.ros.org/gpsd_client/Tutorials/Writing%20a%20Subscriber%20for%20gpsd_client%20%28C%2B%2B%29): Writing Subscriber for gpsd_client is broken as seen below:

![image](https://user-images.githubusercontent.com/32141561/144730864-47131385-8f28-4654-9d18-a6f43a85556f.png)

Please update links.

**Comment by danthony06** [comment]
I've made the changes to the Wiki and updated with the appropriate code.
