### ISSUE TITLE
GPS Params

### ISSUE THREAD

**Issue by ussefdesouky** [swri-robotics/gps_umd#64]
What are the GPS parameters that affect the odometry values?
odometry msg values:
     x:492873.313
     y:5527538.68483

I am using the hector_gazebo gps plugin in the simulation environment.
How can I get the gps odometry values close to the wheel odometry values?

Thanks in advance.

**Comment by danthony06** [comment]
I'm not sure I can easily answer that. In general, you'll need some kind of transform that relates your odometry frame to a map frame. Your SLAM algorithm and the performance of the wheel encoders will determine how accurate this transform is. The GPS will probably be directly provided in the map frame, and then you can compare your odometry estimate to the GPS position measurement.

**Comment by danthony06** [comment]
Closing because of staleness.
