### ISSUE TITLE
Foxy regression

### ISSUE THREAD

**Issue by jacobperron** [swri-robotics/gps_umd#66]
With the latest Foxy release of this package, the build has started failing: https://build.ros2.org/view/Fbin_uF64/job/Fbin_uF64__gpsd_client__ubuntu_focal_amd64__binary/83/

See https://github.com/swri-robotics/gps_umd/pull/61#issuecomment-1238549623 for a report of the offending commit and suggestions for fixing it.

I'm planning to do a Foxy sync soon (maybe next week). If this is not fixed before then, the binary package will be removed from the distribution.

**Comment by jacobperron** [comment]
fyi @danthony06

**Comment by danthony06** [comment]
Okay, I'm looking at it

**Comment by danthony06** [comment]
Branch foxy-devel will be the new release branch for Foxy. I'm blooming it now.

**Comment by danthony06** [comment]
@jacobperron I made a foxy-devel branch that fixes the regression. I bloomed the release, and it's available here:
https://github.com/ros/rosdistro/pull/34631
