### ISSUE TITLE
gpsd_client: Please set frame_id

### ISSUE THREAD

**Issue by nxdefiant** [swri-robotics/gps_umd#7]
The frame_id is currently not set but is required for use with e.g. robot_localization. So please allow to set the frame_id by parameter or just default to "gps".

**Comment by kriskozak** [comment]
I needed a brief distraction, so I addressed this issue on 7-set-frame-id (https://github.com/swri-robotics/gps_umd/tree/7-set-frame-id). @pjreed, please have a look.

**Comment by nxdefiant** [comment]
Awesome, btw I forgot that I already created this issue in ros-drivers/gps_umd#6 a few month ago.

**Comment by pjreed** [comment]
Looks good to me.  Want to make a PR for it?
