### ISSUE TITLE
ROS2 Humble release

### ISSUE THREAD

**Issue by kmhallen** [swri-robotics/gps_umd#70]
Humble is at 1.0.4. Galactic is at 1.0.5. Can Humble be bumped to 1.0.5?

**Comment by danthony06** [comment]
Because We're release Foxy and Humble from different branches the version numbers won't necessarily be in sync as we fix distribution specific bugs. In the next release, I'm going to bump Humble to 2.0.0, and Foxy will remain on 1.x.x branches, and ROS 1 will be on 0.x.x releases.
