### ISSUE TITLE
gpsd_client does not compile on Gentoo

### ISSUE THREAD

**Issue by flabrosse** [swri-robotics/gps_umd#9]
Hi,

When attempting to compile gpsd_client (via the gentoo package, [https://github.com/ros/ros-overlay/issues/279](url)), I get an undefined isnan() in client.cpp.  The fix is to:

`# include <cmath>`

Cheers,

Fred

**Comment by pjreed** [comment]
It's currently compiling with gcc 5.4.0 on Ubuntu 16.04, so the issue probably isn't due to the compiler, but rather due to some transitive dependency missing from headers in Gentoo.  Still, it'd be a good idea to include that, so I'll go ahead and do it.
