### ISSUE TITLE
New release into Rolling

### ISSUE THREAD

**Issue by clalancette** [swri-robotics/gps_umd#92]
This package is currently failing to build on Rolling: https://build.ros2.org/view/Rbin_uN64/job/Rbin_uN64__gpsd_client__ubuntu_noble_amd64__binary/ .

However, trying to build it locally succeeds, so I suspect we just need a new release into Rolling of 2.0.3.  Thanks in advance!

**Comment by danthony06** [comment]
Thanks for letting me know, I'll take a look today.

**Comment by danthony06** [comment]
Released it here: https://github.com/ros/rosdistro/pull/40249

**Comment by clalancette** [comment]
> Released it here: [ros/rosdistro#40249](https://github.com/ros/rosdistro/pull/40249)

Thank you very much!
