### ISSUE TITLE
Releasing version 2.0.4?

### ISSUE THREAD

**Issue by ivanperez-keera** [swri-robotics/gps_umd#95]
Hi,

The lastest release was made in September 2023. There's been a bug fix since and no new releases.

Could you please make a new release?

We need `gps_msgs` for Space ROS, which we are releasing in a few days (tomorrow is our build day), so it'd be great to depend on a version that includes the very latest bug fixes. Thanks!

**Comment by danthony06** [comment]
I'm not sure, but `gps_msgs` is in the package.xml for the packages in this repo. Can you be more specific about what's going on?

**Comment by ivanperez-keera** [comment]
The last release of this package was made in September 2023. There is a tag 2.0.3 with that date.

A new bug fix has been included since then. It's also been quite a long time.

Would the maintainers be able to make a release 2.0.4 that includes that change?

It would help packages that depend on `gps_msgs` depend on a specific version, instead of depending on a moving `HEAD` or a commit hash (which is not a great version number).

**Comment by danthony06** [comment]
2.0.4 is released, and bloomed for Rolling, Iron, and Humble.
