### ISSUE TITLE
Release 1.0.10 is marked latest in github, but should be 2.0.3?

### ISSUE THREAD

**Issue by ivanperez-keera** [swri-robotics/gps_umd#96]
Release 1.0.10 is marked as the latest release on github but, unless I'm misunderstanding something, I think 2.0.3 should be marked as the latest.

**Comment by danthony06** [comment]
We're releasing both ROS 1 and ROS 2 code out of this repository. The ROS 1
releases are marked 1.x, and ROS 2 is marked 2.x, but GitHub doesn't really
have that concept, hence why a 1.x release may be marked as the latest
release.
